#if !canImport(ObjectiveC)
import XCTest

extension HelperTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HelperTests = [
        ("testMarkdownSafe", testMarkdownSafe),
    ]
}

extension LibraryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LibraryTests = [
        ("testFindPlaylist", testFindPlaylist),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HelperTests.__allTests__HelperTests),
        testCase(LibraryTests.__allTests__LibraryTests),
    ]
}
#endif
