name: LibPlaylisterTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        image: 
          - "swift:5.1"
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Swift Version
      run: swift --version
    - name: Debug Build
      run: swift build -v -c debug
    - name: Debug Test
      run: swift test -v -c debug
